using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TheKiwiCoder;

public class SetAnimation : ActionNode
{
    [Header("Type of value to set")]
    public bool useRandomAnim; // Using the random number generated by RandomAnimation.cs
    public bool floatAnimation; // Setting a float number variable in the animator
    public bool intAnimation; // Setting a int number variable in the animator
    public bool boolAnimation; // Setting a bool variable in the animator
    public bool triggerAnimation; // Setting a bool variable in the animator
    
    [Header("Data depending on value type")]
    public string animationToPlay; // The name of the animator variable
    public float floatValue; // The float number to set when using the float option from above
    public int intValue; // the int number to set when using the int option from above
    public bool stateValue; // the state to set when using the bool option from above

    protected override void OnStart() {
    }

    protected override void OnStop() {
    }

    /// <summary>
    /// Setting the correct animator variable depending on the input in the editor
    /// </summary>
    /// <returns></returns>
    protected override State OnUpdate() {
        if (floatAnimation) {
            context.animator.SetFloat(animationToPlay, floatValue);
        }
        else if (intAnimation)
        {
            context.animator.SetInteger(animationToPlay, intValue);
        }
        else if (boolAnimation) {
            context.animator.SetBool(animationToPlay, stateValue);
        }
        else if (triggerAnimation) {
            context.animator.SetTrigger(animationToPlay);
        }
        else if (useRandomAnim) {
            context.animator.SetInteger("RandomAnim", blackboard.randomAnimInt);
        }
        return State.Success;
    }
}
